version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-shopcart
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: shopcart
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
